# -*- coding: utf-8 -*-
"""column_groups

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1km2c3NW8t5OL5wDCOaJ9N7qD_g687lJT
"""

import pandas as pd

df=pd.read_csv("master_clauses.csv")

filename_col="Filename"

answer_cols=[col for col in df.columns if "Answer" in col]
context_cols=[col for col in df.columns if col not in answer_cols+[filename_col]]


binary_cols=[]
entity_cols=[]

for col in answer_cols:

  values=(df[col].dropna().astype(str).str.strip().unique())

  value_set=set(values)

  if value_set.issubset({"Yes","No"}):
    binary_cols.append(col)
  else:
    entity_cols.append(col)
print("Context Columns: ",len(context_cols))
print("Answer Columns: ",len(answer_cols))
print("Binary Columns: ",len(binary_cols))
print("Entity Columns: ",len(entity_cols))

presence_stats = []

for col in binary_cols:
    clause_name = (
        col.replace("-Answer", "")
           .replace("- Answer", "")
           .strip()
    )

    yes_count = (df[col].astype(str).str.strip() == "Yes").sum()
    no_count = (df[col].astype(str).str.strip() == "No").sum()

    presence_stats.append({
        "clause_name": clause_name,
        "yes_count": yes_count,
        "no_count": no_count,
        "presence_rate": yes_count / len(df)
    })

presence_df = pd.DataFrame(presence_stats)