# -*- coding: utf-8 -*-
"""fingerprint_builder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avAkPoOAPpdBOCz2hDVRO5oD9cNJ8UeZ
"""

import pandas as pd
import re


def to_snake_case(text):
    text = text.lower()
    text = text.replace("/", "_")
    text = text.replace("-", "_")
    text = text.replace(" ", "_")
    text = re.sub(r"[^a-z0-9_]", "", text)
    text = re.sub(r"_+", "_", text)
    return text.strip("_")


def build_contract_fingerprints(df):
    filename_col = "Filename"

    answer_cols = [col for col in df.columns if "Answer" in col]

    binary_cols = []
    entity_cols = []

    for col in answer_cols:
        values = (
            df[col]
            .dropna()
            .astype(str)
            .str.strip()
            .unique()
        )
        value_set = set(values)

        if value_set.issubset({"Yes", "No"}):
            binary_cols.append(col)
        else:
            entity_cols.append(col)

    binary_fingerprint = pd.DataFrame()
    binary_fingerprint["filename"] = df[filename_col]

    for col in binary_cols:
        clean_name = col.replace("-Answer", "").replace("- Answer", "").strip()
        snake_name = to_snake_case(clean_name)
        binary_fingerprint[snake_name] = (
            df[col].astype(str).str.strip().map({"Yes": True, "No": False})
        )

    entity_fingerprint = pd.DataFrame()
    entity_fingerprint["filename"] = df[filename_col]

    for col in entity_cols:
        clean_name = col.replace("-Answer", "").replace("- Answer", "").strip()
        snake_name = to_snake_case(clean_name)
        entity_fingerprint[snake_name] = df[col]

    fingerprints = entity_fingerprint.merge(
        binary_fingerprint,
        on="filename",
        how="left"
    )

    derived_cols = [
        "renewal_term",
        "notice_period_to_terminate_renewal",
        "expiration_date",
        "effective_date",
        "governing_law"
    ]

    for col in derived_cols:
        if col in fingerprints.columns:
            fingerprints[f"has_{col}"] = fingerprints[col].notna()

    return fingerprints