import json
from datetime import datetime


def build_report_payload(
    filename,
    risk_score,
    risk_band,
    detected_clauses_df,
    risk_driver_table,
    evidence_df
):
    detected_present = detected_clauses_df[
        detected_clauses_df["detected"] == True
    ].copy()

    top_evidence = (
        evidence_df
        .sort_values(["clause_name", "rank"])
        .groupby("clause_name")
        .head(2)
        .copy()
    ) if not evidence_df.empty else evidence_df.copy()

    evidence_records = []

    if not top_evidence.empty:
        evidence_records = top_evidence[
            ["clause_name", "rank", "similarity_score", "chunk_id", "evidence_text"]
        ].to_dict(orient="records")

    risk_driver_records = (
        risk_driver_table.to_dict(orient="records")
        if not risk_driver_table.empty
        else []
    )

    return {
        "report_generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")+ " UTC",
        "contract_file": filename,
        "risk_score": int(risk_score),
        "risk_band": risk_band,
        "detected_clause_count": int(len(detected_present)),
        "detected_clauses": detected_present["clause_name"].tolist(),
        "risk_driver_count": int(len(risk_driver_table)),
        "risk_drivers": risk_driver_records,
        "evidence": evidence_records
    }


def generate_rule_based_report(payload):
    lines = []

    lines.append("# MeridianIQ End-to-End Contract Review Report")
    lines.append("")
    lines.append(f"**Generated At:** {payload['report_generated_at']}")
    lines.append(f"**Contract File:** {payload['contract_file']}")
    lines.append("")

    lines.append("## 1. Overall Risk Assessment")
    lines.append("")
    lines.append(f"**Risk Score:** {payload['risk_score']}/100")
    lines.append(f"**Risk Band:** {payload['risk_band']}")
    lines.append(f"**Detected MVP Clauses:** {payload['detected_clause_count']}")
    lines.append(f"**Triggered Risk Drivers:** {payload['risk_driver_count']}")
    lines.append("")

    lines.append("## 2. Detected Clauses")
    lines.append("")
    if payload["detected_clauses"]:
        for clause in payload["detected_clauses"]:
            lines.append(f"- {clause}")
    else:
        lines.append("- No MVP clauses detected.")
    lines.append("")

    lines.append("## 3. Key Risk Drivers")
    lines.append("")
    if payload["risk_drivers"]:
        for driver in payload["risk_drivers"]:
            lines.append(
                f"- **{driver['clause_name']}** "
                f"({driver['severity']}, {driver['risk_domain']}): "
                f"{driver.get('business_description', '')}"
            )
            lines.append(
                f"  - Recommended Action: "
                f"{driver.get('recommendation', 'Review with stakeholders.')}"
            )
    else:
        lines.append("- No major risk drivers triggered.")
    lines.append("")

    lines.append("## 4. Supporting Evidence")
    lines.append("")
    if payload["evidence"]:
        for item in payload["evidence"]:
            evidence = str(item["evidence_text"]).strip()[:900]

            lines.append(f"### {item['clause_name']} — Evidence Rank {item['rank']}")
            lines.append("")
            lines.append(f"**Similarity Score:** {item['similarity_score']}")
            lines.append("")
            lines.append(f"> {evidence}...")
            lines.append("")
    else:
        lines.append("- No evidence chunks available.")
    lines.append("")

    lines.append("## 5. Disclaimer")
    lines.append("")
    lines.append(
        "This report is generated by an AI-assisted contract intelligence system. "
        "It is intended for preliminary business review only and should not be treated as legal advice."
    )

    return "\n".join(lines)


def save_report_payload(payload, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)