# -*- coding: utf-8 -*-
"""text_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKiKl7n6wusuV6J61doF7N004HC-U9ja
"""

import re
import pandas as pd


def clean_contract_text(text):
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n+", "\n\n", text)
    text = text.strip()
    return text


def split_long_paragraph(paragraph, max_chars=1500):
    sentences = re.split(r"(?<=[.!?])\s+", paragraph)
    chunks = []
    current_chunk = ""

    for sentence in sentences:
        sentence = sentence.strip()

        if not sentence:
            continue

        if len(current_chunk) + len(sentence) + 1 <= max_chars:
            current_chunk = (current_chunk + " " + sentence).strip()
        else:
            if current_chunk:
                chunks.append(current_chunk)
            current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk)

    return chunks


def chunk_contract_text(text, max_chars=1500):
    paragraphs = re.split(r"\n\s*\n", text)

    chunks = []
    current_chunk = ""

    for paragraph in paragraphs:
        paragraph = paragraph.strip()

        if not paragraph:
            continue

        if len(paragraph) > max_chars:
            if current_chunk:
                chunks.append(current_chunk)
                current_chunk = ""

            chunks.extend(split_long_paragraph(paragraph, max_chars=max_chars))

        elif len(current_chunk) + len(paragraph) + 2 <= max_chars:
            current_chunk = (current_chunk + "\n\n" + paragraph).strip()

        else:
            if current_chunk:
                chunks.append(current_chunk)
            current_chunk = paragraph

    if current_chunk:
        chunks.append(current_chunk)

    chunk_records = []

    for idx, chunk in enumerate(chunks):
        chunk_records.append({
            "chunk_id": idx,
            "chunk_text": chunk,
            "char_count": len(chunk),
            "word_count": len(chunk.split())
        })

    return pd.DataFrame(chunk_records)